export const data = [
  {
    image:
      "https://www.cartoq.com/wp-content/uploads/2020/08/toyota-rav4-1.jpg",
    title: "Toyota RAV4",
    year: 2021,
    capacity: 4,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 440,
  },
  {
    image:
      "https://www.financialexpress.com/wp-content/uploads/2019/10/BMW-3-Series-2019-small.jpg?w=480",
    title: "BMW 3 Series",
    year: 2020,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 8.2,
    trans: "Automatic",
    price: 820,
  },
  {
    image:
      "https://www.carblogindia.com/wp-content/uploads/2017/04/volkswagen-polo-gt-sport-front-angle.jpg",
    title: "Volkswagen Polo",
    year: 2016,
    capacity: 4,
    fuel_type: "Diesel",
    mileage: 9.5,
    trans: "Manual",
    price: 360,
  },
  {
    image:
      "https://www.drivespark.com/img/2023/08/toyota-fortuner-cover-1691303191.jpg",
    title: "Toyota Fortuner",
    year: 2018,
    capacity: 6,
    fuel_type: "Diesel",
    mileage: 5.3,
    trans: "Automatic",
    price: 600,
  },
  {
    image:
      "https://www.indiacarnews.com/wp-content/uploads/2014/05/Mercedes-Benz-S-Class.jpg",
    title: "Mercerdes S-Class",
    year: 2023,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 4.6,
    trans: "Automatic",
    price: 1100,
  },
  {
    image:
      "https://english.cdn.zeenews.com/sites/default/files/2022/10/26/1108513-gmc-hummer-ev-suv.jpg",
    title: "Hummer EV",
    year: 2023,
    capacity: 7,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 965,
  },
  {
    image:
      "https://images.drive.com.au/driveau/image/upload/c_fill,f_auto,g_auto,h_1080,q_auto:eco,w_1920/v1/cms/uploads/lyufxratdwk6orjpytxx",
    title: "Toyota RAV4",
    year: 2021,
    capacity: 4,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 440,
  },
  {
    image:
      "https://www.cartoq.com/wp-content/uploads/2020/08/toyota-rav4-1.jpg",
    title: "Toyota RAV4",
    year: 2021,
    capacity: 4,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 440,
  },
  {
    image:
      "https://www.financialexpress.com/wp-content/uploads/2019/10/BMW-3-Series-2019-small.jpg?w=480",
    title: "BMW 3 Series",
    year: 2020,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 8.2,
    trans: "Automatic",
    price: 820,
  },
  {
    image:
      "https://www.carblogindia.com/wp-content/uploads/2017/04/volkswagen-polo-gt-sport-front-angle.jpg",
    title: "Volkswagen Polo",
    year: 2016,
    capacity: 4,
    fuel_type: "Diesel",
    mileage: 9.5,
    trans: "Manual",
    price: 360,
  },
  {
    image:
      "https://www.drivespark.com/img/2023/08/toyota-fortuner-cover-1691303191.jpg",
    title: "Toyota Fortuner",
    year: 2018,
    capacity: 6,
    fuel_type: "Diesel",
    mileage: 5.3,
    trans: "Automatic",
    price: 600,
  },
  {
    image:
      "https://www.indiacarnews.com/wp-content/uploads/2014/05/Mercedes-Benz-S-Class.jpg",
    title: "Mercerdes S-Class",
    year: 2023,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 4.6,
    trans: "Automatic",
    price: 1100,
  },
  {
    image:
      "https://english.cdn.zeenews.com/sites/default/files/2022/10/26/1108513-gmc-hummer-ev-suv.jpg",
    title: "Hummer EV",
    year: 2023,
    capacity: 7,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 965,
  },
  {
    image:
      "https://images.drive.com.au/driveau/image/upload/c_fill,f_auto,g_auto,h_1080,q_auto:eco,w_1920/v1/cms/uploads/lyufxratdwk6orjpytxx",
    title: "Toyota RAV4",
    year: 2021,
    capacity: 4,
    fuel_type: "Hybrid",
    mileage: 6.1,
    trans: "Automatic",
    price: 440,
  },

  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b5/R8_Coupe_V10_performance-1.jpg",
    title: "Audi R8",
    year: 2021,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 6.71,
    trans: "Automatic",
    price: 440,
  },
  {
    image:
      "https://www.thrustzone.com/wp-content/uploads/2022/09/Jeep-wrangler-willys-4xe-1-1200x788.jpg",
    title: "Jeep Wrangler",
    year: 2018,
    capacity: 5,
    fuel_type: "Petrol",
    mileage: 12.1,
    trans: "Automatic",
    price: 339,
  },
  {
    image:
      "https://cdn.carbuzz.com/gallery-images/2023-nissan-gt-r-nismo-lateral-view-carbuzz-1022696-1600.jpg",
    title: "Nissan GT-r",
    year: 2019,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 13.1,
    trans: "Automatic",
    price: 445,
  },
  {
    image:
      "https://images.unsplash.com/photo-1653788194740-2bfa458194dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1331&q=80",
    title: "BMW M3",
    year: 2019,
    capacity: 4,
    fuel_type: "Petrol",
    mileage: 14.1,
    trans: "Automatic",
    price: 645,
  },
  {
    image:
      "https://imgd-ct.aeplcdn.com/640X480/cw/ucp/stockApiImg/87A3KUH_9f3b551c7fa54e058bf3378dcd899815_1_29741186.jpg?q=80",
    title: "Range rover Vogue",
    year: 2012,
    capacity: 7,
    fuel_type: "Petrol",
    mileage: 12.1,
    trans: "Automatic",
    price: 745,
  },
  {
    image: "https://www.drivespark.com/images/2022-06/2022-bmw-x1-8.jpg",
    title: "BMW X1",
    year: 2018,
    capacity: 5,
    fuel_type: "Petrol",
    mileage: 16.1,
    trans: "Automatic",
    price: 495,
  },
];
